### PR TITLE
PNC-CLI Make-Mead automation

### PR DESCRIPTION
**Pull request by pkralik**
Creating build configurations with PNC-CLI IP tooling configuration files

### CODE REVIEW

**Comment by jbartece** [comment]
@thauser Hi, could you review the PR and merge it then, please?

**Comment by janinko** [comment]
If nobody objects, I'll merge this PR.

**Comment by jbartece** [comment]
Nobody objected for 27 days :-). Feel free to merge it

**Comment by thauser** [comment]
Sorry about the delay on merging this!

**Pull request merged**
